name: iHelp Functional / Unit Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
        node_version: 16.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - run: yarn install
      - run: yarn test
